[programs.localnet]
reearn_program = "DNWtXxdTAjjgZckwCq8sXKnoxGFdD5riNZn4q4zTRqD4"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "~/.config/renec/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
